---
- name: "install Kerbrute"
  shell: go install github.com/ropnop/kerbrute@master

- name: "install gobuster"
  shell: go install github.com/OJ/gobuster/v3@latest

- name: "install anew"
  shell: go install -v github.com/tomnomnom/anew@latest
  
- name: "install unfurl"
  shell: go install github.com/tomnomnom/unfurl@latest

- name: "install gowitness"
  shell: go install github.com/sensepost/gowitness@latest
