---
- name: "Load gnome terminal profiles"
  shell: dconf load /org/gnome/terminal/legacy/profiles:/ < "{{ role_path }}/files/gnome-terminal-profiles.dconf"

- name: "load gnome shell keybindings"
  shell: dconf load / < "{{ role_path }}/files/keybindings.dconf"

- name: "load gnome tiling assistant keybindings"
  shell: dconf load / < "{{ role_path }}/files/tiling-assistant.dconf"

- name: "load gnome dash-to-dock config"
  shell: dconf load / < "{{ role_path }}/files/dash-to-dock.dconf"

