---
- name: "Copy ZSHRC"
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}"

- name: "Load gnome terminal profiles"
  shell: dconf load /org/gnome/terminal/legacy/profiles:/ < "{{ role_path }}/files/gnome-terminal-profiles.dconf"

